// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB14tkOauyImcnsivfcQntphlesGjjzGRA',
    appId: '1:1008833299015:web:529cf0727583b43d336762',
    messagingSenderId: '1008833299015',
    projectId: 'flutter-course-7013d',
    authDomain: 'flutter-course-7013d.firebaseapp.com',
    storageBucket: 'flutter-course-7013d.appspot.com',
    measurementId: 'G-0L9LLG2Q49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYCMmBwPgc7ya3JUyXKEqO4Mqs0WqSOHc',
    appId: '1:1008833299015:android:1ffd9508d10b1abf336762',
    messagingSenderId: '1008833299015',
    projectId: 'flutter-course-7013d',
    storageBucket: 'flutter-course-7013d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALWsniLWqM6fRxx3lc3J7sGmDge_oQnS0',
    appId: '1:1008833299015:ios:c8f92e35f015ac2b336762',
    messagingSenderId: '1008833299015',
    projectId: 'flutter-course-7013d',
    storageBucket: 'flutter-course-7013d.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALWsniLWqM6fRxx3lc3J7sGmDge_oQnS0',
    appId: '1:1008833299015:ios:c8f92e35f015ac2b336762',
    messagingSenderId: '1008833299015',
    projectId: 'flutter-course-7013d',
    storageBucket: 'flutter-course-7013d.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB14tkOauyImcnsivfcQntphlesGjjzGRA',
    appId: '1:1008833299015:web:c7d8f0ee3283d98d336762',
    messagingSenderId: '1008833299015',
    projectId: 'flutter-course-7013d',
    authDomain: 'flutter-course-7013d.firebaseapp.com',
    storageBucket: 'flutter-course-7013d.appspot.com',
    measurementId: 'G-YVD27DQ7ZP',
  );
}
